import type { Entry } from './types';

/**
 * The starter library. Written in the spirit of mental-rehearsal practice:
 * a clear first-person intention, a specific sensory scene to inhabit, and an
 * elevated feeling to close on. Nothing here is a medical or scientific claim —
 * it's language for a personal practice, and all of it is editable in-app.
 */
export const LIBRARY: Entry[] = [
  // ── Confidence ──────────────────────────────────────────────────────────
  {
    id: 'c1',
    theme: 'confidence',
    affirmation: 'I am someone who speaks clearly about what I know.',
    scene: [
      'A room with more people in it than you expected.',
      'You are already standing. Your feet are flat and warm on the floor.',
      'You begin, and your voice comes out at the pace you chose — not faster.',
      'Someone at the back leans in slightly to hear you better.',
      'You finish the thought you meant to finish. You let the silence sit.',
    ],
    seal: 'The steadiness of having said the true thing, plainly.',
  },
  {
    id: 'c2',
    theme: 'confidence',
    affirmation: 'I meet the hard part of the day first.',
    scene: [
      'The thing you have been circling for a week is open in front of you.',
      'It is early. Nobody needs anything from you yet.',
      'You start on it before you have decided you are ready.',
      'Twenty minutes in, the resistance has quietly gone somewhere else.',
      'By the time the day properly begins, the hard part is behind you.',
    ],
    seal: 'The lightness of a day with nothing heavy left in it.',
  },
  {
    id: 'c3',
    theme: 'confidence',
    affirmation: 'I do not need everyone in the room to agree with me.',
    scene: [
      'You say the thing that is slightly unpopular.',
      'You notice the small drop in the temperature of the room.',
      'You stay exactly where you are. Nothing in your body scrambles to fix it.',
      'Someone disagrees. You hear it all the way through before answering.',
      'You leave the room still on good terms with yourself.',
    ],
    seal: 'The quiet of not having traded your position for approval.',
  },
  {
    id: 'c4',
    theme: 'confidence',
    affirmation: 'I carry myself like the work is already mine.',
    scene: [
      'You walk in somewhere you once thought you would not belong.',
      'You are not auditioning. You are just here, doing the thing.',
      'Your hands are loose. Your shoulders are down where they should be.',
      'Someone asks you a question as though you are the person to ask.',
      'You answer. It does not occur to you to apologise first.',
    ],
    seal: 'The ordinariness of belonging somewhere you wanted to be.',
  },
  {
    id: 'c5',
    theme: 'confidence',
    affirmation: 'I recover quickly when something goes wrong.',
    scene: [
      'Something lands badly. There is that first drop in the stomach.',
      'You feel it fully — you do not pretend it did not happen.',
      'And then, sooner than usual, you are already thinking about the next move.',
      'By the afternoon it has become information rather than a verdict.',
      'You sleep that night without rehearsing it.',
    ],
    seal: 'The relief of a mistake that stayed the size it actually was.',
  },
  {
    id: 'c6',
    theme: 'confidence',
    affirmation: 'I ask for what the work is worth.',
    scene: [
      'You name the number, and then you stop talking.',
      'The pause is longer than comfortable. You let it be long.',
      'You do not fill it by making yourself smaller.',
      'The conversation continues from the number you said, not below it.',
      'You walk out having been straightforward about your own value.',
    ],
    seal: 'The calm of having asked without flinching.',
  },
  {
    id: 'c7',
    theme: 'confidence',
    affirmation: 'I am allowed to take up the space I actually occupy.',
    scene: [
      'A table. You sit down and put both forearms on it.',
      'You are not perched on the edge of the chair.',
      'When you speak you do not rush to get it over with.',
      'When you are finished speaking you do not add a nervous little laugh.',
      'The room reorganises slightly around someone who is simply present.',
    ],
    seal: 'The ease of taking up your own amount of room.',
  },
  {
    id: 'c8',
    theme: 'confidence',
    affirmation: 'I finish things.',
    scene: [
      'The project that has been ninety percent done for a month.',
      'You open it one more time, knowing this is the last time.',
      'The final ten percent is boring. You do it anyway.',
      'You send it, or ship it, or hand it over.',
      'The file closes. The tab closes. It is out of your hands and it is done.',
    ],
    seal: 'The specific satisfaction of a thing that is finished, not abandoned.',
  },
  {
    id: 'c9',
    theme: 'confidence',
    affirmation: 'I keep the promises I make to myself.',
    scene: [
      'It is the hour when you said you would do the thing.',
      'Every reason not to is available and all of them sound sensible.',
      'You do it anyway, badly, for the amount of time you promised.',
      'Something in you registers that you are a person who does what they said.',
      'That registration happens again tomorrow, and the day after.',
    ],
    seal: 'The self-trust of being reliable to yourself.',
  },
  {
    id: 'c10',
    theme: 'confidence',
    affirmation: 'I let my work be seen before it is perfect.',
    scene: [
      'The draft is good and not finished. You know both of these things.',
      'You attach it and write a short message with no long apology in it.',
      'You send it.',
      'The feedback that comes back is useful and survivable.',
      'The work gets better because it left the room.',
    ],
    seal: 'The freedom of not needing it to be flawless to exist.',
  },
  {
    id: 'c11',
    theme: 'confidence',
    affirmation: 'I say no cleanly, without a trail of explanation.',
    scene: [
      'The ask arrives. It is reasonable, and it is not yours.',
      '"I can\'t take that on." One sentence.',
      'You do not build a case. You do not offer three alternatives.',
      'The other person adjusts, the way people generally do.',
      'Your week stays the shape you designed it to be.',
    ],
    seal: 'The spaciousness of a week you still own.',
  },
  {
    id: 'c12',
    theme: 'confidence',
    affirmation: 'I am not behind. I am on my own timeline.',
    scene: [
      'You see the news about someone doing what you want to do.',
      'The old comparison starts up, familiar as a song.',
      'You notice it, and it does not get to run the morning.',
      'You go back to your own work, which is at its own stage.',
      'You get a little further along a road that is genuinely yours.',
    ],
    seal: 'The steadiness of a pace you are not apologising for.',
  },

  // ── Calm ────────────────────────────────────────────────────────────────
  {
    id: 'k1',
    theme: 'calm',
    affirmation: 'I move through today without hurrying.',
    scene: [
      'You are walking somewhere and you are not walking fast.',
      'There is time. There turns out to be, genuinely, time.',
      'You arrive and you are not out of breath.',
      'The first thing you do on arriving is sit down for a moment.',
      'The day proceeds at the speed of someone who is not chasing it.',
    ],
    seal: 'The unhurried feeling of enough time.',
  },
  {
    id: 'k2',
    theme: 'calm',
    affirmation: 'My mind is quiet when I ask it to be.',
    scene: [
      'You close your eyes in the middle of an ordinary afternoon.',
      'The noise is still there for a few seconds.',
      'Then it thins out, the way a room empties after people leave.',
      'What is left is your breath and the temperature of the air.',
      'You stay there for as long as you like, and then you open your eyes.',
    ],
    seal: 'The stillness underneath the noise, always there.',
  },
  {
    id: 'k3',
    theme: 'calm',
    affirmation: 'I let the thing I cannot control be out of my hands.',
    scene: [
      'The outcome you have been gripping is somewhere out in the world.',
      'You picture opening your hand and letting it be where it is.',
      'It does not fall. It just stops being held.',
      'Your jaw unclenches slightly. Your breathing gets longer.',
      'The day carries on and you are in it rather than above it, worrying.',
    ],
    seal: 'The lightness of putting down what was never yours to hold.',
  },
  {
    id: 'k4',
    theme: 'calm',
    affirmation: 'I am not required to respond immediately.',
    scene: [
      'A message arrives that pulls at you.',
      'You read it. You feel the pull to answer in the next ten seconds.',
      'You put the phone face down and go and do something with your hands.',
      'An hour later you answer, and the answer is better.',
      'Nothing bad happened in the hour.',
    ],
    seal: 'The calm of a pace you set rather than inherit.',
  },
  {
    id: 'k5',
    theme: 'calm',
    affirmation: 'I sleep easily and wake rested.',
    scene: [
      'The room is dark and the right kind of cool.',
      'The day is finished. You are not still negotiating with it.',
      'You feel the weight of your own body going down into the bed.',
      'The last thought is unremarkable and then there are no more thoughts.',
      'You wake before the alarm, already on the good side of tired.',
    ],
    seal: 'The soft weight of rest that actually arrived.',
  },
  {
    id: 'k6',
    theme: 'calm',
    affirmation: 'I do one thing at a time.',
    scene: [
      'One window open. One page. One task.',
      'The others are still there, and they are not here.',
      'Twenty minutes pass and you did not check anything.',
      'The work goes deeper than it normally gets to go.',
      'You finish, and then you choose the next single thing.',
    ],
    seal: 'The clarity of a mind pointed in one direction.',
  },
  {
    id: 'k7',
    theme: 'calm',
    affirmation: 'I am steady even when things around me are not.',
    scene: [
      'Something urgent is happening and people are moving quickly.',
      'You notice your own breathing first, before anything else.',
      'You do the next useful thing rather than the most dramatic thing.',
      'Someone looks over at you and visibly settles.',
      'The urgency passes, as it does, and you did not spend yourself on it.',
    ],
    seal: 'The ballast of being the calm thing in the room.',
  },
  {
    id: 'k8',
    theme: 'calm',
    affirmation: 'I let this day be ordinary.',
    scene: [
      'Nothing remarkable is scheduled.',
      'You are not trying to make it into anything.',
      'Light moves across a wall over the course of the morning.',
      'You eat something slowly and taste it.',
      'The day is small and good and you are not asking it to be more.',
    ],
    seal: 'The quiet pleasure of an unremarkable day.',
  },
  {
    id: 'k9',
    theme: 'calm',
    affirmation: 'My breath is long, and it slows everything down with it.',
    scene: [
      'Four counts in through the nose. The ribs widen.',
      'A pause at the top that is not strained.',
      'Six counts out, longer than the in-breath, all the way to empty.',
      'Somewhere around the fourth round the shoulders come down.',
      'You are running at a slower speed than you were two minutes ago.',
    ],
    seal: 'The settled, low feeling of a nervous system at rest.',
  },
  {
    id: 'k10',
    theme: 'calm',
    affirmation: 'I put things down at the end of the day.',
    scene: [
      'The last piece of work of the day, closed deliberately.',
      'You say to yourself, in words: that is where I stopped.',
      'The evening starts, and it is a different thing from the day.',
      'When a work thought arrives you note it for tomorrow and let it go.',
      'By the time it gets dark you are actually off.',
    ],
    seal: 'The clean edge between the day and the evening.',
  },
  {
    id: 'k11',
    theme: 'calm',
    affirmation: 'I have nowhere else I need to be right now.',
    scene: [
      'Wherever you are, you stop planning the next place.',
      'You notice three things you can hear.',
      'You notice the temperature on the backs of your hands.',
      'The future thins out and the present becomes the only well-lit room.',
      'You stay there a while, because there is nowhere else to go.',
    ],
    seal: 'The full, quiet arrival of being here.',
  },
  {
    id: 'k12',
    theme: 'calm',
    affirmation: 'I meet difficulty without bracing against it.',
    scene: [
      'Something uncomfortable is happening and it is going to keep happening.',
      'You feel yourself start to tighten, and then you deliberately soften.',
      'You stay in the room with it rather than leaving your own body.',
      'It is unpleasant. It is also, it turns out, bearable.',
      'It passes through, the way weather does.',
    ],
    seal: 'The strength of staying soft in something hard.',
  },

  // ── Health ──────────────────────────────────────────────────────────────
  {
    id: 'h1',
    theme: 'health',
    affirmation: 'I treat my body like something I am responsible for.',
    scene: [
      'You are making the first food of the day and it is real food.',
      'You are not eating it standing up over the sink.',
      'Water, first, before anything else.',
      'Later you move, in whatever way you move, and it is not a punishment.',
      'You go to bed at a time you chose in advance.',
    ],
    seal: 'The self-respect of being well looked after — by you.',
  },
  {
    id: 'h2',
    theme: 'health',
    affirmation: 'Movement is something I look forward to.',
    scene: [
      'The first two minutes are the worst and you know it in advance.',
      'You go anyway, and the two minutes pass the way they always do.',
      'Ten minutes in your breathing has found its rhythm.',
      'There is a point where the effort stops being negotiation and becomes enjoyment.',
      'Afterwards you are warm and loose and glad, as usual.',
    ],
    seal: 'The good tiredness of a body that has been used.',
  },
  {
    id: 'h3',
    theme: 'health',
    affirmation: 'I am at home in my own body.',
    scene: [
      'You catch your reflection and do not immediately start auditing.',
      'You notice instead that your shoulders are down and your breathing is easy.',
      'You move through the day without commentary about how you look doing it.',
      'Your body is the thing you live in, not the thing you are judged on.',
      'You end the day on good terms with it.',
    ],
    seal: 'The peace of being inside your own life rather than watching it.',
  },
  {
    id: 'h4',
    theme: 'health',
    affirmation: 'I have steady energy through the whole day.',
    scene: [
      'The morning starts and the energy is even rather than spiked.',
      'Through the middle of the day it stays level.',
      'At three in the afternoon there is no cliff.',
      'You are still thinking clearly at five.',
      'The tiredness that comes in the evening is the ordinary, earned kind.',
    ],
    seal: 'The evenness of a day with no crash in it.',
  },
  {
    id: 'h5',
    theme: 'health',
    affirmation: 'I rest before I am forced to.',
    scene: [
      'You notice the early signal — the reread sentence, the short temper.',
      'You stop at the signal rather than three hours past it.',
      'You do nothing for twenty minutes and you do not feel guilty about it.',
      'You come back to the work with your mind actually working.',
      'The day does not end in the ditch.',
    ],
    seal: 'The wisdom of stopping early enough.',
  },
  {
    id: 'h6',
    theme: 'health',
    affirmation: 'I am strong, and I am getting stronger.',
    scene: [
      'The weight, or the hill, or the distance, that used to be hard.',
      'It is not hard today. It is just what you do now.',
      'You remember when it was the edge of what you could manage.',
      'The edge has moved, quietly, over weeks you barely noticed.',
      'You go slightly past it again today.',
    ],
    seal: 'The confidence of a body that keeps becoming more capable.',
  },
  {
    id: 'h7',
    theme: 'health',
    affirmation: 'I eat in a way that leaves me feeling well.',
    scene: [
      'A plate that looks like actual food, with colour on it.',
      'You eat it sitting down, without a screen.',
      'You stop when you are satisfied rather than when the plate is empty.',
      'An hour later you feel clear rather than heavy.',
      'There is no negotiation and no guilt in any of it.',
    ],
    seal: 'The simple comfort of being well fed.',
  },
  {
    id: 'h8',
    theme: 'health',
    affirmation: 'My body gets to repair while I sleep.',
    scene: [
      'The light in the room has been low for an hour already.',
      'Your body temperature drops slightly and you feel the pull of sleep.',
      'You let it take you rather than staying up past it.',
      'Through the night the work of repair happens without your involvement.',
      'You wake up and something is measurably better than it was.',
    ],
    seal: 'The trust of letting your body do what it knows how to do.',
  },
  {
    id: 'h9',
    theme: 'health',
    affirmation: 'I go outside every day.',
    scene: [
      'You step out and the air is a different temperature than the inside air.',
      'Daylight on your face, even if the sky is grey.',
      'You walk without a destination for a few minutes.',
      'Something in your head reorders itself while you are walking.',
      'You come back in slightly different than you went out.',
    ],
    seal: 'The reset of having been outdoors.',
  },
  {
    id: 'h10',
    theme: 'health',
    affirmation: 'I notice what my body is telling me.',
    scene: [
      'You pause in the middle of the day and check in, briefly.',
      'Tight jaw. Held shoulders. Shallow breathing. You find one of them.',
      'You do the small correcting thing, right then.',
      'You check again an hour later.',
      'The accumulation that usually builds up by evening does not build up.',
    ],
    seal: 'The attentiveness of being in conversation with yourself.',
  },
  {
    id: 'h11',
    theme: 'health',
    affirmation: 'I am gentle with myself on the days that are harder.',
    scene: [
      'Today the body is not cooperating the way it does on good days.',
      'You adjust the plan downward without turning it into a failure.',
      'You do the smaller version of the thing.',
      'You are as kind to yourself as you would be to someone you love.',
      'Tomorrow is allowed to be different.',
    ],
    seal: 'The kindness of not being at war with a hard day.',
  },
  {
    id: 'h12',
    theme: 'health',
    affirmation: 'I am building habits that will still be here in a year.',
    scene: [
      'The thing you do today is small enough to be unremarkable.',
      'It is the same small thing you did yesterday.',
      'You picture the same small thing happening three hundred times.',
      'You picture the person at the other end of those three hundred days.',
      'You come back to today, and do the small thing.',
    ],
    seal: 'The quiet compounding of something done daily.',
  },

  // ── Relationships ───────────────────────────────────────────────────────
  {
    id: 'r1',
    theme: 'relationships',
    affirmation: 'I listen all the way to the end.',
    scene: [
      'Someone is telling you something and you already have your reply ready.',
      'You set the reply down and keep listening instead.',
      'They get to the part they were actually trying to say — the second thing.',
      'You ask about that rather than delivering what you had prepared.',
      'The conversation goes somewhere neither of you planned.',
    ],
    seal: 'The closeness of having actually heard someone.',
  },
  {
    id: 'r2',
    theme: 'relationships',
    affirmation: 'I say the warm thing out loud.',
    scene: [
      'You think something good about a person who is in front of you.',
      'The usual thing would be to think it and not say it.',
      'You say it, plainly, without making it a joke.',
      'Something shifts in their face.',
      'It costs you four seconds and they carry it around all day.',
    ],
    seal: 'The warmth of a kind thing that made it out of your head.',
  },
  {
    id: 'r3',
    theme: 'relationships',
    affirmation: 'I repair quickly after friction.',
    scene: [
      'The conversation went badly and both of you left it unfinished.',
      'The old pattern would be three days of careful distance.',
      'Instead you go back within the day and say the first honest sentence.',
      'It is awkward for about a minute.',
      'Then it is over, and the thing between you is intact.',
    ],
    seal: 'The relief of something mended before it hardened.',
  },
  {
    id: 'r4',
    theme: 'relationships',
    affirmation: 'I am easy to be around.',
    scene: [
      'You walk into a room where people you like already are.',
      'You are not carrying anything in that needs managing.',
      'The conversation is light and then, at some point, it is not light.',
      'You are good company in both registers.',
      'People are glad you came. You can tell.',
    ],
    seal: 'The ease of good company, given and received.',
  },
  {
    id: 'r5',
    theme: 'relationships',
    affirmation: 'I reach out first.',
    scene: [
      'Someone you have not spoken to in months comes into your head.',
      'You do not wait for a reason or a better time.',
      'You send the message that just says you were thinking of them.',
      'They answer, and it is like no time passed.',
      'You make a plan and, this time, it actually happens.',
    ],
    seal: 'The gladness of a connection you kept alive.',
  },
  {
    id: 'r6',
    theme: 'relationships',
    affirmation: 'I let people see how I actually am.',
    scene: [
      'Someone asks how you are and you are about to say "fine."',
      'You tell them the real answer instead, in one honest sentence.',
      'They do not flinch or fix it. They just stay with you.',
      'The conversation gets more real from there.',
      'You leave it less alone than you arrived.',
    ],
    seal: 'The relief of not performing being fine.',
  },
  {
    id: 'r7',
    theme: 'relationships',
    affirmation: 'I give people the benefit of the doubt.',
    scene: [
      'The short message arrives and your first reading is the worst one.',
      'You try the second reading: they were busy, or tired, or elsewhere.',
      'You respond to the second reading.',
      'It turns out the second reading was the true one.',
      'A whole imagined conflict never gets born.',
    ],
    seal: 'The lightness of not carrying a grudge you invented.',
  },
  {
    id: 'r8',
    theme: 'relationships',
    affirmation: 'I am present with the people in front of me.',
    scene: [
      'The phone is in another room. Not face down — another room.',
      'You are looking at the person who is speaking.',
      'There is nowhere else the conversation has to compete with.',
      'They say something they would not have said to a distracted person.',
      'An hour goes by and neither of you notices.',
    ],
    seal: 'The rare, full attention of two people actually there.',
  },
  {
    id: 'r9',
    theme: 'relationships',
    affirmation: 'I hold my boundaries without going cold.',
    scene: [
      'Someone asks for more than you have to give.',
      'You say no, and you say it warmly.',
      'You do not punish them for asking, and you do not give in.',
      'The warmth and the limit turn out to be able to exist together.',
      'The relationship is still good on the other side of it.',
    ],
    seal: 'The integrity of a limit held kindly.',
  },
  {
    id: 'r10',
    theme: 'relationships',
    affirmation: 'I forgive the thing I have been carrying.',
    scene: [
      'The old grievance, which you can still describe in detail.',
      'You picture setting it down — not agreeing with it, just setting it down.',
      'It stays where you put it.',
      'The room in your chest where it lived is now empty and strangely light.',
      'You think about that person and the first feeling is no longer heat.',
    ],
    seal: 'The spaciousness of putting down something old.',
  },
  {
    id: 'r11',
    theme: 'relationships',
    affirmation: 'I am generous without keeping score.',
    scene: [
      'You do the helpful thing and you do not log it.',
      'Nobody is told. There is no ledger being kept.',
      'The good feeling you get is the whole return, and it is enough.',
      'It happens again next week with someone else.',
      'You are the kind of person this is simply true about.',
    ],
    seal: 'The clean feeling of giving without an invoice.',
  },
  {
    id: 'r12',
    theme: 'relationships',
    affirmation: 'I let myself be helped.',
    scene: [
      'Someone offers, and the reflex is to say you have got it.',
      'You say yes instead.',
      'They help, and they are visibly glad to be useful.',
      'The thing gets done faster and you are less depleted.',
      'You notice that being helped did not cost you anything.',
    ],
    seal: 'The unexpected closeness of having accepted help.',
  },

  // ── Growth ──────────────────────────────────────────────────────────────
  {
    id: 'g1',
    theme: 'growth',
    affirmation: 'I am becoming someone slightly different than I was.',
    scene: [
      'You picture yourself a year from today, in an ordinary moment.',
      'Not a triumph — a Tuesday. Making coffee. Answering a message.',
      'The difference is in how that person carries themselves.',
      'Something they used to find hard has become unremarkable to them.',
      'You come back to this morning, which is where that gets built.',
    ],
    seal: 'The pull of a version of you that is already forming.',
  },
  {
    id: 'g2',
    theme: 'growth',
    affirmation: 'I am willing to be a beginner.',
    scene: [
      'The new thing, on day one, where you are visibly not good.',
      'You do it in front of people anyway.',
      'You ask the obvious question rather than pretending to know.',
      'Week three arrives and you are no longer the worst in the room.',
      'You remember that every good thing you can do started exactly here.',
    ],
    seal: 'The freedom of not needing to already be good at it.',
  },
  {
    id: 'g3',
    theme: 'growth',
    affirmation: 'I choose the harder, better path when it is offered.',
    scene: [
      'Two options. One is comfortable and you know exactly how it goes.',
      'The other is the one you will be glad about in five years.',
      'You take the second one while still feeling the pull of the first.',
      'It is harder in exactly the ways you predicted.',
      'You are, later, entirely glad.',
    ],
    seal: 'The conviction of a decision made from the long view.',
  },
  {
    id: 'g4',
    theme: 'growth',
    affirmation: 'I learn faster than I break.',
    scene: [
      'The attempt fails, in public, in a way that stings.',
      'You go looking for the lesson before you go looking for comfort.',
      'You find one specific thing to do differently.',
      'You try again inside the same week, not the same month.',
      'The second attempt is measurably better than the first.',
    ],
    seal: 'The momentum of failing forward rather than sideways.',
  },
  {
    id: 'g5',
    theme: 'growth',
    affirmation: 'I do the work when nobody is watching.',
    scene: [
      'An early hour. No audience. No one to be impressed.',
      'You do the unglamorous repetition that the thing actually requires.',
      'It is boring, and boring is the price, and you pay it.',
      'This happens on a day nobody will ever know about.',
      'It is the day the whole thing is actually built on.',
    ],
    seal: 'The private integrity of unwitnessed work.',
  },
  {
    id: 'g6',
    theme: 'growth',
    affirmation: 'I change my mind when the evidence changes.',
    scene: [
      'Something you believed turns out to be wrong.',
      'The first feeling is the defensive one. You let it pass.',
      'You say out loud that you were wrong about it.',
      'Nothing bad happens. You are, if anything, more trusted.',
      'You now believe the more accurate thing.',
    ],
    seal: 'The lightness of not defending an old position.',
  },
  {
    id: 'g7',
    theme: 'growth',
    affirmation: 'I am curious about the thing I have been avoiding.',
    scene: [
      'The subject you have been steering around for months.',
      'You turn and look directly at it, just to see.',
      'It is smaller than the version you had been avoiding.',
      'You find one small true thing about it.',
      'The avoidance loses its grip a little.',
    ],
    seal: 'The relief of looking straight at something.',
  },
  {
    id: 'g8',
    theme: 'growth',
    affirmation: 'I let go of the story that has stopped being true.',
    scene: [
      'The old sentence about yourself: I am the kind of person who —',
      'You notice it running, the way you notice a fridge humming.',
      'You check it against the last two years of actual evidence.',
      'It does not hold up anymore.',
      'You put it down, and the day carries on without it.',
    ],
    seal: 'The openness of a self-description you outgrew.',
  },
  {
    id: 'g9',
    theme: 'growth',
    affirmation: 'I am building something that takes years.',
    scene: [
      'Today\'s piece of it is small and does not look like much.',
      'You set it in place anyway.',
      'You picture the hundreds of small pieces already behind you.',
      'You picture the shape they are slowly making.',
      'You add today\'s piece and stop, and that is the whole job today.',
    ],
    seal: 'The patience of something being built properly.',
  },
  {
    id: 'g10',
    theme: 'growth',
    affirmation: 'I take the opportunity before I feel ready.',
    scene: [
      'The door opens earlier than you expected it to.',
      'Everything in you wants another six months of preparation.',
      'You say yes while the readiness is still missing.',
      'You become ready inside the thing rather than before it.',
      'Afterwards you cannot imagine having waited.',
    ],
    seal: 'The aliveness of having said yes too early.',
  },
  {
    id: 'g11',
    theme: 'growth',
    affirmation: 'I notice how far I have already come.',
    scene: [
      'You think back to yourself two years ago, honestly.',
      'The things that were genuinely hard for that person.',
      'Most of them are not hard for you now. You had stopped noticing.',
      'You let that register properly instead of moving straight past it.',
      'You start today from that, rather than from the deficit.',
    ],
    seal: 'The solid ground of progress already made.',
  },
  {
    id: 'g12',
    theme: 'growth',
    affirmation: 'Today is one of the days it gets built on.',
    scene: [
      'This morning is not a preamble to the real thing.',
      'It is a unit of the real thing.',
      'What you do in the next few hours is the material.',
      'You picture the day as it goes well — specifically, concretely.',
      'Then you open your eyes and go and have that day.',
    ],
    seal: 'The readiness of a day you have already walked through once.',
  },
];
